server:
  port: 8092
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user
  registry:
    address: zookeeper://192.168.31.131:2181?backup=192.168.31.131:2182,192.168.31.131:2183