server:
  port: 8093
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

mybatis-plus:
  type-aliases-package: org.gavin.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.gavin.mapper: debug

dubbo:
  scan:
    basePackages: org.gavin
  application:
    name: provider-sso
  registry:
    address: zookeeper://192.168.31.131:2181?backup=192.168.31.131:2182,192.168.31.131:2183
  protocol:
    name: dubbo
    port: 20880